# Generated by Django 4.2.7 on 2024-01-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_transportation', models.DateField()),
                ('time_transportation', models.TimeField()),
                ('sedan', models.BooleanField(default=False)),
                ('suv', models.BooleanField(default=False)),
                ('bus', models.BooleanField(default=False)),
                ('van', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'form',
            },
        ),
    ]
