# Generated by Django 4.2.7 on 2024-01-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_transportation', models.DateField()),
                ('time_transportation', models.TimeField()),
                ('vehicle', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('passenger', models.IntegerField()),
            ],
            options={
                'db_table': 'form',
            },
        ),
    ]
